setup(name='progsnap',
      version='0.1.0',
      description='Library for reading Progsnap datasets',
      url='https://github.com/cloudcoderdotorg/progsnap',
      author='David Hovemeyer',
      author_email='david.hovemeyer@gmail.com',
      license='MIT',
      packages=['progsnap'],
      zip_safe=False)
